car/urls.py
from django.contrib import admin
from django.urls import path
from cat.views import CarsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', CarsView.as_view()),
]

cat/models.py
from django.db import models

# Create your models here.
class Car(models.Model):
    AUTO = 1
    ROBOT = 2
    MECHANIC = 3
    VARIATOR = 4
    KPP_CHOICES = [(AUTO, 'Автоматическая'),
                   (ROBOT, 'Роботизированная'),
                   (MECHANIC, 'Механическая'),
                   (VARIATOR, 'Вариатор'),
    ]



    vendor = models.CharField("Марка", max_length=64)
    name = models.CharField("Модель", max_length=64)
    year = models.PositiveIntegerField("Год",)
    transmission = models.SmallIntegerField("КПП", choices=KPP_CHOICES)
    color = models.CharField("Цвет", max_length=64)

    def __str__(self):
        return f'{self.vendor} {self.name} ({self.year})'

cat/views.py
from django.db.models import Q
from django.views.generic import TemplateView

from cat.models import Car


class CarsView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        params = self.request.GET
        query = Q()
        for key, value in params.items():
            if value and key in vars(Car):
                query &= Q(**{key: value})
        return {"cars": Car.objects.filter(query)}

templates/index.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <nav class="navbar navbar-expand navbar-dark bg-primary">
        <a href="" class="navbar-brand">Проект PWS_D10</a>
    </nav>

<div class="row h-100">
    <div class="col-2 bg-secondary p-4">

        <form action="" class="sidebar-nav">
            <div class="form-group">
                <label>Марка</label>
                <input type="text" name="vendor">
            </div>
            <div class="form-group">
                <label>Модель</label>
                <input type="text" name="name">
            </div>
            <div class="form-group">
                <label>Год выпуска</label>
                <input type="number" name="year">
            </div>
            <div class="form-group">
                <label>Трансмиссия</label>
                <select name="transmission">
                  <option value="" selected>Выберите коробку передач</option>
                  <option value="3">Механика</option>
                  <option value="1">Автомат</option>
                  <option value="2">Робот</option>
                  <option value="4">Вариатор</option>
                </select>
            </div>
            <div class="form-group">
                <label>Цвет</label>
                <input type="text" name="color">
            </div>
            <div class="form-group">
                <input class="bg-danger" type="submit" value="Применить фильтр" >
        </form>
    </div>
</div>

<div class="col-10">
    <table class="table" border="1">
        <thead class="thead-light">
            <tr>
                <th>Марка</th>
                <th>Модель</th>
                <th>Год выпуска</th>
                <th>Трансмиссия</th>
                <th>Цвет</th>
            </tr>
        </thead>
{% for car in cars %}

      <tr>
          <td>{{ car.vendor }}</td>
          <td>{{ car.name }}</td>
          <td>{{ car.year }}</td>
          <td>{{ car.get_transmission_display }}</td>
          <td>{{ car.color }}</td>
      </tr>
{% empty %}
      <p>В настоящее время машин с таким набором параметров нет в наличии</p>

{% endfor %}
</div>